namespace VoiceAssistant.Domain;

/// <summary>
/// Interface for a handler that executes a specific voice command intent.
/// </summary>
public interface ICommandHandler
{
    /// <summary>
    /// Gets the specific intent name (e.g., "TakeScreenshot", "GetTime") that this handler processes.
    /// This should match the IntentName generated by the IIntentParser.
    /// </summary>
    string HandledIntentName { get; }

    /// <summary>
    /// Executes the command associated with the handled intent.
    /// </summary>
    /// <param name="intent">The parsed intent details, including parameters.</param>
    /// <param name="token">Cancellation token.</param>
    /// <returns>A CommandResult indicating success/failure and any output for TTS.</returns>
    Task<CommandResult> ExecuteAsync(IntentResult intent, CancellationToken token = default);
} 